### ISSUE TITLE
Conflict between RebindAllTheKeys 1.2.0 and OptiFabric 1.13.16

### ISSUE THREAD

**Issue by Compsogbrickus** [Minenash/RebindAllTheKeys#11]
Minecraft crashes on startup with newest Fabric and Fabric API versions with the following error:
`org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector fixKeybindsAfterAmecsIsRemoved(Lnet/minecraft/class_304;Lnet/minecraft/class_3675$class_306;)V in rebind_all_the_keys.mixins.json:GameOptionsMixin from mod rebind_all_the_keys failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap rebind-all-the-keys-refmap.json`

Recompiling RebindAllTheKeys without the GameOptionsMixin resolves the crash, but this is obviously not a good solution. A slightly more detailed crash report is attached, but the game refuses to generate a full report.

[crash_report_partial.txt](https://github.com/Minenash/RebindAllTheKeys/files/10056693/crash_report_partial.txt)

**Comment by Minenash** [comment]
Due to closed nature of optifine, adding support or fixing conflicts is infeasible. If you still wish to use this mod, I'd recommend optifine alternatives like Iris and Sodium
