### ISSUE TITLE
Drop stack modifier in inventories

### ISSUE THREAD

**Issue by boggymc** [Minenash/RebindAllTheKeys#19]
The drop stack modifier currently doesn't work in inventories

**Comment by muzikbike** [comment]
Can confirm this to be the case.

**Comment by Minenash** [comment]
Fixed in next release

**Comment by Minenash** [comment]
Fixed in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
