### ISSUE TITLE
Feature request: add ability to rebind shift in inventories

### ISSUE THREAD

**Issue by Cloudperry** [Minenash/RebindAllTheKeys#2]
I have a custom mechanical keyboard with a pretty non-standard keyboard layout and this mod is really great for me. However it would be super useful to be able to rebind shift clicking items to something else. I have already changed my sneak key to ' because that's what I have in the place of my left shift key. My shift key is in a pretty convenient position as well but it would be better if this mod could rebind inventory shift clicking to some custom key + click or alternatively sneak key + click.

Btw [this wiki page](https://minecraft.fandom.com/wiki/Controls#Java_Edition) could be useful for checking what bindings can't be changed by this mod.

**Comment by Minenash** [comment]
I forgot to close this when the version the added this was released 4 months ago. Though I'm releasing an update tonight that fixes a pretty major problem (the one linked above)
