### ISSUE TITLE
Gamemode Switcher not working

### ISSUE THREAD

**Issue by tsumi7** [Minenash/RebindAllTheKeys#23]
![image](https://github.com/Minenash/RebindAllTheKeys/assets/90137856/989ace42-2724-4271-bd38-0684644e21a5)
`[` correctly activates the debug menu but holding it and tapping `]` does nothing. Using version 1.4.0+1.20.2 off of Modrinth.

**Comment by tsumi666** [comment]
?

**Comment by YoshiRulz** [comment]
Not sure why you closed this OP. It's definitely present in version 1.4.0 on Minecraft 1.20.4. `Debug Key`+`Gamemode Switcher` will cycle the menu but not open it. `Debug Key`+F4 will open the menu but not cycle it.

edit: Might be tied to the specific key? I was testing with `Debug Key` = Numpad 3 and `Gamemode Switcher` = Numpad 4, but it works as expected with `Debug Key` = F3 and `Gamemode Switcher` = M.
