### ISSUE TITLE
Incompatible with Amecs

### ISSUE THREAD

**Issue by tsumi7** [Minenash/RebindAllTheKeys#24]
When changing the `F3`/`F4` setting it is not saved immediately, the behavior is as follows:
- Set `F3` to `[`
- Set `F4` to `]`
- Restart game
- Press `[` -> `]` nothing happens

**Comment by Minenash** [comment]
Fixed in next release (Amecs fully works now also!!)

**Comment by Minenash** [comment]
Fixed in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
