### ISSUE TITLE
"Double Tap to Fly" toggle

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#26]
Currently, there's an option to toggle whether double-pressing the forward button should enable sprinting or not, but no equivalent toggle for flying.
![2023-12-28_01 58 50](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/d10153ee-0e9f-4cf5-bebe-96e9b34c5ed5)

Of course, since there's no keybind for flying in vanilla, it may be advisable to implement one. Perhaps also a secondary key for sprinting like what RandomPatches added (and if both are bound to the same key by default, this is when the "Double Tap" toggle becomes relevant - otherwise they act as normal sprint/fly keys).
![2023-12-28_01 54 50](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/bb356799-0bee-48c8-bfa2-1eb881507172)

**Comment by Minenash** [comment]
Not fully sure about a secondary key for sprinting, but a dedicated fly key and a double-jump toggle for fly sounds good!

**Comment by Minenash** [comment]
Codded, will be in next release

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
