### ISSUE TITLE
Ability to have a separate keybind for dismounting

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#27]
RandomPatches allowed for a separate dismount keybind from the rest of sneaking's functionality, but said mod hasn't updated past 1.16. Could this mod add such a thing?
![2023-12-28_01 55 02](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/077c4f86-2c1a-4cc6-8bcc-69850efc233e)

**Comment by Minenash** [comment]
omg, how I have I not added this yet. Yes 100%, this will be added. I'm actually having this same annoyance recently when flying airships

**Comment by muzikbike** [comment]
Instead of displaying as being bound to "Left Shift" by default, it could display as being bound to "Sneak", implying that this control is bound to whatever Sneak is bound to be default, but can be rebound to any other key.

**Comment by Minenash** [comment]
It's actually not easy to implement this. The server is the one that checks to see if the player is sneaking. So you have to send a packet telling the server you're sneaking and then send another packet to what you're actually doing. But this seems buggy right now, gonna try to get it to work reliably, but no guarantees

**Comment by muzikbike** [comment]
I assume the same is true of #32 and #33 (and possibly #39 and #40)?

Can't remember if RandomPatches absorbed the "dedicated dismount key" functionality from a separate mod (it certainly makes no mention of it and I could be mixing it up with something else), but a glance at the code in its repository does reveal relevant code in RPConfig.java, ClientPlayerEntityMixin.java, ClientPlayNetworkHandlerMixin.java and PlayerInputC2SPacketMixin.java that seems relevant (but I am not at all qualified to understand). I should probably check RandomPatches more thoroughly to see if this particular feature is noticeably buggy at all...

**Comment by Minenash** [comment]
> I assume the same is true of https://github.com/Minenash/RebindAllTheKeys/issues/32 and https://github.com/Minenash/RebindAllTheKeys/issues/33 (and possibly https://github.com/Minenash/RebindAllTheKeys/issues/39 and https://github.com/Minenash/RebindAllTheKeys/issues/40)?

I don't believe so, but those 4 won't be in the next update either way

**Comment by Minenash** [comment]
Nevermind, I misunderstood the packet that was being sent. The packet sent for riding (PlayerInputC2SPacket) is different than the ones for moving normally. It's actually a really simple thing when changing the "sneaking" key in this packet doesn't impact sneaking in general.

**Comment by Minenash** [comment]
Codded, will be in next release

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
