### ISSUE TITLE
"Persist after key release" toggle for sprinting and sneaking

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#28]
Currently in vanilla, when the sneak key is released, the player will instantly stop sneaking. However, if the sprint key is released, the player will continue to sprint until they stop moving. Could this mod implement a toggle of some sort that allows sneaking to behave more like sprinting or vice versa in this aspect?

**Comment by Minenash** [comment]
Interesting idea, I can do that

**Comment by Minenash** [comment]
Codded, will be in next release

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
