### ISSUE TITLE
Bind "Hotbar Previous/Next" to scroll wheel movement by default, instead of having it as an override

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#30]
Mojang don't seem to be willing to permit changing this: https://bugs.mojang.com/browse/MC-268283

If #31 is done, we could have this bound to the two normal scroll wheel directions by default.

**Comment by Minenash** [comment]
This already exists in the mod?

**Comment by muzikbike** [comment]
Wait, does it? I might not have checked the controls list thoroughly enough.

**Comment by Minenash** [comment]
Should be in the inventory section

**Comment by muzikbike** [comment]
I see it now. Was thinking that instead of being an override unbound by default, that it would instead be displayed as bound to scrolling by default and rebindable from there (which would require #31):
![image](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/e8d1e7c5-6fde-4802-8e10-b9fe84d4d4a8)

**Comment by Minenash** [comment]
The problem was that I looked into it before and couldn't figure out how to do it, I can always look again though (having scroll as a bindable thing)

**Comment by muzikbike** [comment]
With respect to the most recent commit, it may be advisable to use negative mouse buttons for scroll wheel movement instead, since the USB standard permits button inputs up to 65535. I understand this is an absurd nitpick, but LWJGL should soon allow for more than eight mouse buttons to be usable (https://github.com/glfw/glfw/pull/2423), and since negative mouse buttons will never be accessible this is one way to put them to use instead.

**Comment by Minenash** [comment]
Codded, will be in next release

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
