### ISSUE TITLE
Ability to bind controls to scroll wheel movement

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#31]
This goes hand in hand with #30.

Currently, we can only bind game controls to either keyboard buttons or mouse buttons - scroll wheel movement is off limits. It doesn't look like this is going to be changing any time soon either: https://bugs.mojang.com/browse/MC-268284

Having the ability to bind things to the scroll wheel would be handy. By default, scrolling up and scrolling down would be linked to hotbar item switching (#30).

Some mice, such as the Logitech MX Master and the A4Tech 4D mice and trackballs, have two scroll wheels - one for standard vertical scrolling, and the other for horizontal scrolling. It'd be preferable if we could bind things to both vertical scrolling and horizontal scrolling for completeness's sake, but I don't have any mice with a horizontal scroll wheel to actually test this.

**Comment by Minenash** [comment]
Codded, will be in next release

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
