### ISSUE TITLE
Text in game mode switcher is incorrect

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#35]
![2023-12-27_12 48 50](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/8ce34dac-3fca-471c-843c-08ca752a8194)

Compare vanilla:
![2024-04-02_14 47 21](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/9f224e2b-907d-48cb-bd6a-48edc3675e12)

**Comment by Minenash** [comment]
I noticed this when I was working on the mouse scrolling binds a couple weeks ago. It looked like in one of the updates, both lines started to you the same render method and I didn't catch that, so I was overwriting both renders, not just the one anymore.

Fixed in the next release

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
