### ISSUE TITLE
Right-click inventory controls cannot be rebound

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#36]
Right clicking allows for half of a stack (rounded up) to be picked up by the cursor, as well as for a stack held by the cursor to deposit one item into a give slot (or dropped, if the cursor is outside of the inventory screen). This cannot be rebound in vanilla or via this mod. It does not follow the "Use Item/Place Block" key binding, unlike the pick block functionality in inventories, which does.

Ideally, the two functionalities ("deposit one" and "pick up half") should be bindable separately, even if they both default to right click.

**Comment by muzikbike** [comment]
![2024-04-02_21 35 02](https://github.com/Minenash/RebindAllTheKeys/assets/52297970/515445f8-a078-48a3-91d8-2b86f59bf79a)

**Comment by Minenash** [comment]
> Ideally, the two functionalities ("deposit one" and "pick up half") should be bindable separately, even if they both default to right click.

This might happen at some point, but not in the next release

**Comment by Minenash** [comment]
I've added the ability to rebind the screen's primary (left-click) and secondary (right-click). I kept it screen level, as I can't see a reason to separate the general screen and inventory-specific ones, and also to try to keep it working with any mods that add screens.

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
