### ISSUE TITLE
Left-click inventory controls cannot be rebound

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#38]
Much like in #36, it's not possible to rebind left-click inventory stuff either. They don't follow Attack/Destroy, unlike the inventory controls that follow Pick Block.

Affects picking up items from a slot, putting them in a slot, and switching between the contents of the cursor and a slot.

**Comment by Minenash** [comment]
I've added the ability to rebind the screen's primary (left-click) and secondary (right-click). I kept it screen level, as I can't see a reason to separate the general screen and inventory-specific ones, and also to try to keep it working with any mods that add screens.

**Comment by Minenash** [comment]
Released in Version 1.5.0. [Modrinth](<https://modrinth.com/mod/rebind-all-the-keys/version/1.5.0+1.20.2>) [Curseforge](<https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys/files/5242211>) [Github](<https://github.com/Minenash/RebindAllTheKeys/releases/tag/v1.5.0%2B1.20.2>)
