### ISSUE TITLE
Hold/Toggle/Persistent option for flying

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#51]
Not sure if I'd use this myself, but it'd make sense for this to be consistent with sneaking and sprinting given that there's now a toggle key.

**Comment by Minenash** [comment]
I disagree, since holding it and toggle are separate already, and "persistent flying" doesn't make sense, This would really just be a "enable toggle keybind" which is the same thing as just setting the keybind
