### ISSUE TITLE
Only permit use of primary button for enchanting

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#52]
For some reason, using any mouse button in the enchanting interface will act as a confirmation of said enchantment, rather than only the left button (https://bugs.mojang.com/browse/MC-270272). Would it be possible to only have "Screen Primary" count as a valid control for doing enchantments, or would this be out of the scope of the mod?

**Comment by Minenash** [comment]
I think that would be out of scope
