### ISSUE TITLE
Allow double-tap sprinting to work when in midair

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#54]
https://bugs.mojang.com/browse/MC-68453 - another vanilla bug RandomPatches fixed with its keybind reworks. Not sure if it'd be in scope here but it's one that has irritated me for a while.

**Comment by Minenash** [comment]
If RandomPatches fixes it, does another mod need to? because I want to have vanilla behavior still be default, this would require adding another option. Ik this extra option wouldn't be as much of a deal if your single-tap/double-tap issue was implemented, but yeah
