### ISSUE TITLE
Sneaking and "Quick move" conflict

### ISSUE THREAD

**Issue by Fabian42** [Minenash/RebindAllTheKeys#7]
Apparently #2 was implemented, but now I can't sneak anymore if both settings use the same key.

**Comment by AspieGamer13** [comment]
same issue. can't sneak or dismount unless I rebind that key OR the move all items key.
the main reason I have this mod is to disable the narrator toggle only.

**Comment by Fabian42** [comment]
It's actually worse, because lots of Shift actions in inventories still use Shift: preparing to craft a full stack with the recipe book, preparing to trade a full stack with villagers, MiniHUD's shulker box preview, …  
So for now I've bound this to Y and got into the habit of always pressing Shift and Y together, because it's too confusing otherwise to constantly switch between the two and remember which one does what.

If someone knows another mod that lets me rebind more keys, please tell me. I mainly use this mod to have F3+B not be so close to F3+N and Alt+F3 not be so close to Alt+F4 anymore.

**Comment by Minenash** [comment]
Update will release tonight
