### ISSUE TITLE
Re-adding render distance shortcut

### ISSUE THREAD

**Issue by Fabian42** [Minenash/RebindAllTheKeys#8]
I used F3+F a lot before 1.19 removed it for some reason. It would be nice to have it back.

**Comment by Minenash** [comment]
Interesting. The keybind itself is still there, I guess I can re-implement the ability

**Comment by Minenash** [comment]
Added, will be in tonight's release

**Comment by Fabian42** [comment]
Nice, thank you! Since I've made the report, I've gotten it back with some other mod already, but I'm not quite sure which one. (: I think it's "BetterF3".
